### ISSUE TITLE
hope it could support subscribe.

### ISSUE THREAD

**Issue by miracomangomanchuria** [v2ray/manual#123]
Hope it could support subscribe. Have you, the honored developer, got a plan for it?

**Comment by young-zy** [comment]
It's a good thing to have subscription function. But as the tag of [https://github.com/v2ray/Planning/issues/59](url) has been set to unplanned, it seems that we can only depend on the third party standard(like v2ray n & ng).
May be the developers would like to focus on the development of core functions rather than developing features that are not so 'important'(which can be developed by others).

**Comment by nicholascw** [comment]
invalid issue
